### ISSUE TITLE
set up Netlify

### ISSUE THREAD

**Issue by Be-ing** [ChicagoDSA/chapter-website#5]
Deployment with [Netlify](http://netlify.com/) is easy to set up but it needs to be done by a repo owner. The only configuration that is needed is to set the environment variable `PAGES_REPO_NWO` in Netlify's web configuration UI to `ChicagoDSA/chapter-website`. Then it will automatically build and deploy with each push to the selected branch. It will also automatically build and deploy previews for every pull request as [demonstrated on my fork](https://github.com/Be-ing/chapter-website/pull/1). No changes to the code in the repository are needed.

**Comment by Be-ing** [comment]
ping @SunilRao01

**Comment by SunilRao01** [comment]
Great, thanks for the heads up @Be-ing

**Comment by nickharrisdev** [comment]
I set up our staging instance here: https://cdsa-staging.netlify.app/ @SunilRao01 @Be-ing 

Also added a note to the documentation about this setup. Let me know & feel free to edit if clarification is needed.
